//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by chat.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_SRVR_EMBEDDED               5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_CCHAT_STATUSBAR              101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDB_TOOLBAR                     128
#define IDR_CLIENTTYPE                  129
#define IDB_MEMBER                      140
#define IDD_CHARSELBOX                  141
#define IDB_TALKERS                     148
#define IDB_MUTEDMEMBER                 149
#define IDD_OPTIONBOX                   152
#define IDI_ICON1                       157
#define IDD_TOPIC                       157
#define IDI_ICON2                       158
#define IDI_ICON3                       159
#define IDI_ICON4                       160
#define IDI_ICON5                       161
#define IDI_ICON6                       162
#define IDB_HOST                        167
#define IDB_SPECTATOR                   168
#define IDD_INTOHELP                    170
#define IDR_MEMBERPOPUPMENU             170
#define IDR_AVATARCONTEXT               175
#define IDR_BODYCONTEXT                 176
#define IDD_SETUPDIALOG                 177
#define IDB_MIKEHEAD                    179
#define IDB_BALLOONS                    180
#define IDD_OPTIONS                     181
#define IDD_PROFILE                     183
#define IDR_MEMBERCONTEXT               185
#define IDD_ROOMLIST                    186
#define IDD_BOTHER                      187
#define IDD_SETTINGSPAGE                189
#define IDD_PERSONALPAGE                190
#define IDD_CHARACTERPAGE               191
#define IDD_BACKGROUNDPAGE              192
#define IDR_ADMIN                       193
#define IDD_KICK                        195
#define IDR_VIEWCONTEXT                 196
#define IDD_NICKNAME                    197
#define IDR_MEMBERADMIN                 198
#define IDD_CHANNEL                     198
#define IDB_BITMAP1                     199
#define IDR_CONNECTING                  200
#define IDB_TIKI                        203
#define IDC_SONGCHECK                   1008
#define IDC_EFFECTCHECK                 1009
#define IDC_VERSION                     1010
#define IDC_CHECK1                      1011
#define IDC_SEARCH_DESCRS               1011
#define IDC_BOTHER                      1011
#define IDC_SAVE                        1011
#define IDC_GETLIST                     1011
#define IDC_CHECK2                      1012
#define IDC_COMICSDATA                  1012
#define IDC_CHECK3                      1013
#define IDC_CHECK4                      1014
#define IDC_CHECK5                      1015
#define IDC_AVATREE                     1016
#define IDC_NICKNAME                    1018
#define IDC_SERVER                      1019
#define IDC_CHARACTER                   1020
#define IDC_REALNAME                    1021
#define IDC_CHANNEL                     1023
#define IDC_PORTNUM                     1026
#define IDC_OPTIONTAB                   1028
#define IDC_AVLIST                      1033
#define IDC_LIST1                       1034
#define IDC_BACKLIST                    1034
#define IDC_PROFILE_EDIT                1035
#define IDC_COMBO1                      1037
#define IDC_CHATROOMS                   1037
#define IDC_SEARCH_SERVERS              1037
#define IDC_PANELS                      1037
#define IDC_BUTTON1                     1038
#define IDC_EXPAND                      1038
#define IDC_GOTO                        1038
#define IDC_EDGE                        1039
#define IDC_COLLAPSE                    1040
#define IDC_SETUPHELP                   1041
#define IDC_ROOM_KEYS                   1042
#define IDC_TOPIC_EDIT                  1042
#define IDC_USER_KEY                    1044
#define IDC_ROOMLIST                    1045
#define IDC_RESET_LIST                  1046
#define IDC_SORT_ROOMS                  1048
#define IDC_REASON                      1052
#define IDC_TOPIC                       1055
#define IDC_BACKPREV                    1057
#define IDC_PREVX                       1058
#define IDC_PREVY                       1059
#define IDC_COMICS                      1061
#define IDC_RADIO2                      1062
#define IDC_LISTCHAN                    1062
#define IDC_ROOM_CAPTION                1065
#define IDC_USER                        1066
#define IDC_CORP                        1067
#define IDC_EDIT1                       1068
#define IDC_NEWNICK                     1068
#define IDC_STATICCHANNEL               1069
#define IDC_STATICNICKNAME              1070
#define IDC_CONCHAN                     1071
#define IDC_KICKMSG                     1072
#define IDC_TIKI                        1073
#define IDC_WARNING                     1074
#define IDC_COPY                        1075
#define IDC_LICENSE                     1077
#define IDC_NEWCHANNEL                  1078
#define IDC_NEWROOM                     1079
#define ID_CANCEL_EDIT_SRVR             32769
#define BIND_IDP_FAILED_TO_AUTO_REGISTER 32774
#define ID_FILE_PREFERENCES             32782
#define ID_ACTIONS_SAY                  32783
#define ID_ACTIONS_THINK                32784
#define ID_ACTIONS_EMOTE                32785
#define ID_ACTIONS_SWITCHVIEWPOINT      32786
#define ID_ACTIONS_ACTION1              32787
#define ID_ACTIONS_ACTION2              32788
#define ID_ACTIONS_ACTION3              32789
#define ID_ACTIONS_ACTION4              32790
#define ID_ACTIONS_ACTION5              32791
#define ID_ACTIONS_ACTION6              32792
#define ID_ACTIONS_ACTION7              32793
#define ID_APP_SAVE_HISTORY             32794
#define ID_APP_SAVE_HISTORY_AS          32795
#define ID_APP_ADD_FAV_PLACE            32796
#define ID_APP_CREATE_SHORTCUT          32797
#define ID_APP_CUT                      32798
#define ID_APP_COPY                     32799
#define ID_APP_PASTE                    32800
#define ID_APP_SELECT_ALL               32801
#define ID_APP_CLEAR_HISTORY            32802
#define ID_CHARACTER_SEL                32804
#define ID_APP_2DVIEW                   32805
#define ID_APP_MAIN                     32808
#define ID_APP_GESTURE                  32809
#define ID_APP_STATUSBAR                32810
#define ID_APP_MOVE_SPLITBAR            32811
#define ID_APP_SHOW_SPECTATORS          32812
#define ID_APP_IGNORE_MEMBERS           32813
#define ID_APP_MEMBER_PROPERTIES        32814
#define ID_APP_FILTER_CONVERSATION      32815
#define ID_APP_HOST_CONTROLS            32817
#define ID_APP_OPTIONS                  32818
#define ID_APP_CHARACTER_SEL            32819
#define ID_APP_ENTRY_POINT              32827
#define ID_APP_OVERVIEW                 32829
#define ID_APP_SMALL_FONT               32831
#define ID_APP_MEDIUM_FONT              32832
#define ID_APP_LARGE_FONT               32833
#define ID_APP_SHOW_ALL_MEMBERS         32834
#define ID_APP_HELP_INDEX               32835
#define ID_APP_MEMBER_SUPPORT           32836
#define ID_APP_CONTEXT_HELP             32837
#define ID_APP_HELP                     32838
#define ID_AVATARCONTEXT_TALKTO         32839
#define ID_AVATARCONTEXT_TALKTOALSO     32840
#define ID_AVATARCONTEXT_GETINFO        32841
#define ID_AVATARCONTEXT_IGNORE         32842
#define ID_AVATARCONTEXT_WAVETO         32843
#define ID_AVATARCONTEXT_PUNCH          32844
#define ID_AVATARCONTEXT_KICK           32844
#define ID_BODYCONTEXT_FREEZE           32850
#define ID_BODYCONTEXT_UNFREEZE         32851
#define ID_BODYCONTEXT_SENDEXPRESSION   32852
#define ID_CHARACTER_SUSAN              32854
#define ID_CHARACTER_TONGUETYED         32855
#define ID_CHARACTER_LANCE              32856
#define ID_CHARACTER_MIKE               32857
#define ID_CHARACTER_CHARACTERSELECTION_JORDAN 32858
#define ID_CHARACTER_JORDAN             32859
#define ID_AVATARCONTEXT_RING           32860
#define ID_BROADCAST_COMICS_INFO        32861
#define ID_SEND_COMICS_DATA             32862
#define ID_APP_BACKGROUND_SEL           32863
#define ID_OPTIONS_ADJUSTPANELSIZE      32864
#define ID_OPTIONS_ADJUSTPANELSIZE_1WIDE 32865
#define ID_OPTIONS_PANELS_1WIDE         32865
#define ID_OPTIONS_ADJUSTPANELSIZE_2WIDE 32866
#define ID_OPTIONS_PANELS_2WIDE         32866
#define ID_OPTIONS_ADJUSTPANELSIZE_3WIDE 32867
#define ID_OPTIONS_ADJUSTPANELSIZE_4WIDE 32868
#define ID_OPTIONS_PANELS_4WIDE         32868
#define ID_OPTIONS_ADJUSTPANELSIZE_5WIDE 32869
#define ID_OPTIONS_PANELS_5WIDE         32869
#define ID_OPTIONS_ADJUSTPANELSIZE_1HIGH 32870
#define ID_OPTIONS_PANELS_1HIGH         32870
#define ID_OPTIONS_ADJUSTPANELSIZE_2HIGH 32871
#define ID_OPTIONS_PANELS_2HIGH         32871
#define ID_OPTIONS_ADJUSTPANELSIZE_3HIGH 32872
#define ID_OPTIONS_PANELS_3HIGH         32872
#define ID_OPTIONS_PANELS_3WIDE         32873
#define ID_SEND_SAY                     32874
#define ID_SEND_THINK                   32875
#define ID_SEND_WHISPER                 32876
#define ID_SEND_RING                    32877
#define ID_ACTIONS_WHISPER              32878
#define ID_OPTIONS_CHANGEPROFILE        32879
#define ID_OPTIONS_PROFILE              32880
#define ID_HELP_TOPICS                  32881
#define ID_VIEW_LIST                    32882
#define ID_VIEW_ICON                    32883
#define ID_VIEW_STATUSBAR               32886
#define ID_EDIT_DELETE                  32889
#define ID_EDIT_SELECTALL               32890
#define ID_OPTIONS_PROMPTFORSAVE        32891
#define ID_FAVORITES_ADDTOFAVORITES     32892
#define ID_FAVORITES_OPENFAVORITES      32893
#define ID_FILE_CREATESHORTCUT          32895
#define ID_MEMBER_RING                  32898
#define ID_MEMBER_GETINFO               32899
#define ID_MEMBER_IGNORE                32900
#define ID_SEND_ACTION                  32901
#define ID_FILE_DISCONNECT              32908
#define ID_VIEW_COMICS                  32909
#define ID_VIEW_TEXT                    32910
#define ID_CHATROOM_LIST                32911
#define ID_VIEW_OPTIONS                 32912
#define ID_VIEW_ADMINMENU               32914
#define ID_ADMINISTRATOR_KICK           32916
#define ID_ADMINISTRATOR_MAKEOPERATOR   32917
#define ID_ADMINISTRATOR_TOPIC          32918
#define ID_SESSION_NEWROOM              32919
#define ID_SESSION_LEAVE                32920
#define ID_SESSION_CONNECT              32921
#define ID_SESSION_DISCONNECT           32922
#define ID_MAKEADMIN                    32923
#define ID_MAKE_ADMIN                   32924
#define ID_REMOVE_ADMIN                 32925
#define ID_TOOLBAR_HELP                 42819
#define ID_TOOLBAR_ADD                  42820
#define ID_TOOLBAR_CUT                  42821
#define ID_TOOLBAR_COPY                 42822
#define ID_TOOLBAR_PASTE                42823
#define ID_TOOLBAR_SHOW                 42824
#define ID_TOOLBAR_MEMBER               42825
#define ID_TOOLBAR_IGNORE               42826
#define ID_TOOLBAR_SAVE                 42827
#define IDS_GESTURE_GREET               52828
#define IDS_GESTURE_HAPPY               52829
#define IDS_GESTURE_FLIRT               52830
#define IDS_GESTURE_SHRUG               52831
#define IDS_GESTURE_SAD                 52832
#define IDS_GESTURE_ANGRY               52833
#define IDS_GESTURE_SILLY               52834
#define IDS_GESTURE_RANDOM              52835
#define ID_NUMPRESENT                   59142
#define IDS_ERR_NOT256COLOR             61204
#define IDS_ERROR                       61205
#define IDS_WARNING                     61206
#define IDS_ERROR_SCENENOTFOUND         61207
#define IDS_ERROR_OUTOFMEMORY           61208
#define IDS_ERROR_RENDERERFAILED        61209
#define IDS_FORMAT_SAY                  61211
#define IDS_FORMAT_THINK                61212
#define IDS_FORMAT_EMOTE                61213
#define IDS_FORMAT_ENTER                61214
#define IDS_FORMAT_LEAVE                61215
#define IDS_ERROR_BADSTAMP              61217
#define IDS_ERROR_BADVERSION            61218
#define IDS_ERROR_CMDINITIALIZECONNECTION 61219
#define IDS_ERROR_INVALID_CID           61220
#define IDS_ERROR_INVALID_JOIN          61221
#define IDS_ERROR_INITIALIZE            61222
#define IDS_ERROR_GESTURE               61223
#define IDS_ERROR_SIZE_MISMATCH         61224
#define IDS_ERROR_REMOVE_KEY            61225
#define IDS_STATUSBAR_MEMBERS           61226
#define IDS_SHARED                      61228
#define IDS_MAIN_TOOLBAR                61229
#define IDS_GEST_TOOLBAR                61230
#define ID_POPUP_PROPERTIES             61231
#define IDS_HELP_FILE                   61231
#define ID_POPUP_FIND                   61234
#define ID_EM_HAPPY                     61446
#define ID_EM_COY                       61447
#define ID_EM_BORED                     61448
#define ID_EM_SCARED                    61449
#define ID_EM_SAD                       61450
#define ID_EM_ANGRY                     61451
#define ID_EM_SHOUT                     61452
#define ID_EM_LAUGH                     61453
#define ID_EM_NEUTRAL                   61454
#define ID_EMOTION_IS                   63000
#define ID_ERR_BAD_ARGS                 63001
#define ID_ERR_NOT_CHATLOC              63002
#define ID_ERR_PROFILE_WRITE            63003
#define ID_KEEP_PANELS                  63004
#define ID_RING_MESG                    63005
#define ID_ERR_CONNECT                  63006
#define ID_ERR_BAD_NICK                 63007
#define ID_ERR_DUPED_NICK               63008
#define ID_ERR_OPEN                     63009
#define ID_ERR_SAVE                     63010
#define ID_ERR_NOT_CHATCONV             63011
#define ID_ERR_BAD_CONV_FIELD           63012
#define ID_ERR_WHERE_SERVER             63013
#define ID_DEFAULT_PROFILE              63014
#define ID_AVATAR_TOOLTIP               63015
#define ID_AVATAR_CREDIT                63016
#define ID_STARRING                     63017
#define ID_DISCONNECTED                 63018
#define ID_CONNECTED                    63019
#define ID_USER_SINGULAR                63020
#define ID_USER_PLURAL                  63021
#define ID_MESSAGE_BOX_TITLE            63022
#define IDS_SHORTCUT                    63023
#define IDS_EXPAND                      63024
#define IDS_COLLAPSE                    63025
#define IDS_FAVORITE                    63026
#define ID_COMP_FONT_NAME               63027
#define ID_COMP_FONT_FILE               63028
#define ID_COMIC_FONT_NAME              63029
#define ID_COMIC_FONT_FILE              63030
#define ID_RULE_SHOUT                   63032
#define ID_RULE_LAUGH                   63033
#define ID_RULE_HAPPY                   63034
#define ID_RULE_SAD                     63035
#define ID_RULE_POINTOTHER              63036
#define ID_RULE_POINTSELF               63037
#define ID_RULE_WAVE                    63038
#define ID_RULE_COY                     63039
#define ID_RULE_ANGRY                   63040
#define ID_RULE_SCARED                  63041
#define ID_RULE_BORED                   63042
#define ID_KICK_MESG                    63043
#define ID_KICK_NO_MESG                 63044
#define ID_ERR_BAD_CHANNEL              63045
#define ID_RL_ROOM_LABEL                63046
#define ID_RL_ROOM_WIDTH                63047
#define ID_RL_NUSERS_LABEL              63048
#define ID_RL_NUSERS_WIDTH              63049
#define ID_RL_DESCR_LABEL               63050
#define ID_RL_DESCR_WIDTH               63051
#define IDS_SENDENABLED                 63052
#define IDS_WHISPERENABLED              63053
#define IDS_OPTIONS                     63054
#define ID_SAY_PREFIX                   63055
#define ID_THINK_PREFIX                 63056
#define ID_WHISPER_PREFIX               63057
#define IDS_ONEITEM                     63058
#define IDS_DISCONNECTMESSAGE           63059
#define IDS_TOOMUCHTEXT                 63060
#define IDS_DEFAULT_BACKDROP            63061
#define IDS_NUM_ROOMS                   63062
#define IDS_SHOWINFO_PREFIX             63063
#define IDS_CANTKICK                    63064
#define ID_CONNECTING                   63065
#define ID_NOCHANNEL                    63066
#define ID_ERR_NO_NICK                  63067
#define IDS_KICKREASON                  63068
#define IDS_ILLEGAL_TO_SEND             63069
#define IDS_1_WIDE                      63072
#define IDS_2_WIDE                      63073
#define IDS_3_WIDE                      63074
#define IDS_4_WIDE                      63075
#define ID_ERR_BANNEDFROMCHAN           63076
#define ID_ERR_CHANNELISFULL            63077
#define ID_ERR_INVITEONLY               63078
#define IDS_DISCONNECTMESSAGE2          63079
#define IDS_NOTCOMICSUSER               63080
#define IDS_UNTITLED                    63081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32926
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
