////////////////////////////////////////////////////
//	Copyright (c) Microsoft Corporation, 1996-97
//
//	Description:
//
//	ChatHistoryProcessor processes Message objects
//	and sends TextElements representing them to the screen
//
//	Author:
//		Kris Nye
////////////////////////////////////////////////////
import java.awt.*;
import java.util.*;

public class ChatHistoryProcessor extends HistoryProcessor
{

	//	internationalized strings
	String SAYS;
	String WHISPERS_TO;
	String S_VERSION;
	String S_LOCAL_TIME;
	String S_ROUND_TRIM_TIME;
	String S_IDENTITY;
	String S_PROFILE;
	String SECONDS;
	String ERROR;
	String THINKS;
	
	//	colors
	Color actionColor = Color.magenta.darker();
	Color fromColor = Color.blue;
	Color hostColor = Color.blue;
	Color textColor = Color.black;
	Color relayColor = fromColor;
	Color whisperColor = Color.cyan.darker();
	Color urlColor = Color.blue.darker();
	Color systemColor = Color.green.darker().darker();
	Color errorColor = Color.red.darker();
	Color roomColor = Color.blue.darker().darker();
	Color ctcpColor = Color.orange.darker().darker();

	int fromIndent = 10;
	int messageIndent = 20;
		
	ChatPanel chatPanel;

	public ChatHistoryProcessor(Vector history, ElementHost display, ChatPanel chatPanel)
	{
		this.chatPanel = chatPanel;
		loadStrings();
		processAll(history, display);
	}

	public void loadStrings()
	{
		SAYS = get("says");
		WHISPERS_TO = get("whispers.to");
		S_VERSION = get("s.version");
		S_LOCAL_TIME = get("s.local.time");
		S_ROUND_TRIM_TIME = get("s.round.trip.time");
		S_IDENTITY = get("s.identity");
		S_PROFILE = get("s.profile");
		SECONDS = get("seconds");
		ERROR = get("error");
		THINKS = get("thinks");
	}

	public String get(String key)
	{
		return chatPanel.get(key);
	}

	protected boolean isCTCP(String message)
	{
		char ctcp = 1;
		if (message != null && message.startsWith(ctcp + ""))
			return true;
		return false;
	}

	protected String trimGarbage(String text)
	{
		if (text.startsWith("# "))	// filter out # appears as messages
			return null;
		if (text.startsWith("(#"))
			text = text.substring(text.indexOf(")") + 1).trim();
		if (text.trim().equals("<Chr>"))	// filter out <Chr> messages
			return null;
		return text;
	}

	public String getRoomName()
	{
		if (chatPanel != null)
			return chatPanel.getRoomName();
		return null;
	}

	protected void processCTCP(String source, String message)
	{
		char ctcp = 1;
		//	trim ctcp char from start and end
		message = message.trim();
		Font font = Static.bold(chatPanel.userFont);
		if (message.startsWith("VERSION"))
		{
			String version = message.substring(8);
			String text = source + S_VERSION + ": " + version;
			display(new TextElement(font, ctcpColor, text, fromIndent));
		}
		else if (message.startsWith("TIME"))
		{
			String time = message.substring(5);
			String text = source + S_LOCAL_TIME + ": " + time;
			display(new TextElement(font, ctcpColor, text, fromIndent));
		}
		else if (message.startsWith("PING"))
		{
			try
			{
				String time = message.substring(4).trim();
				long sent = Long.parseLong(time);
				long delta = System.currentTimeMillis() - sent;
				double deltad = delta / (double)1000;
				String text = source + S_ROUND_TRIM_TIME + ": " + deltad + " " + SECONDS;
				display(new TextElement(font, ctcpColor, text, fromIndent));
			}
			catch(Exception e)
			{
				// NumberFormatException
				System.out.println("Error in processCTCP " + e);
			}
		}
		//	note: this is a fake ctcp command generated by
		//	IRCClient from a 311 server response RPL_WHOISUSER
		else if (message.startsWith("IDENTITY"))
		{
			String text = source + S_IDENTITY + ": " + message.substring(9);
			display(new TextElement(font, ctcpColor, text, fromIndent));
		}
		else if (message.startsWith("ACTION"))
		{
			String text = source + " " + message.substring(7);
			display(new TextElement(font, actionColor, text, fromIndent));
		}
		else if (message.startsWith("SOUND"))
		{
		//	System.out.println("Sound is not yet supported " + message);
		}
	}

	protected void processMSChatMessage(String source, String message)
	{
		if (message.startsWith("# Appears"))
		{
			//	this person is an MSChat user,
			//	store this info so we can getProfile on them from popupMenu
			Room room = chatPanel.getRoom();
			if (room == null)
				return;
			User user = room.getUser(source);
			if (user != null)
				user.setMSChatUser(true);
		}
		else if (message.startsWith("# HeresInfo"))
		{
			Font font = Static.bold(chatPanel.userFont);
			String text = source + S_PROFILE + ": " + message.substring(12);
			display(new TextElement(font, ctcpColor, text, fromIndent));
		}
		else
		{
			System.out.println("Unrecognized MSChat Message:");
			System.out.println("Source:  " + source);
			System.out.println("Message: " + message);
		}
	}

	protected boolean isMSCHATAction(String source, String message)
	{
		if (message == null)
			return false;
		if (message.indexOf("(#") == 0 && message.indexOf("M5") > 0)
		{
			Font font = Static.bold(chatPanel.userFont);
			message = trimGarbage(message);
			if (message == null)
				return true;
			display(new TextElement(font, actionColor, message, fromIndent));
			return true;
		}
		return false;
	}

	protected boolean isMSCHATThink(String source, String message)
	{
		if (message == null)
			return false;
		if (message.indexOf("(#") == 0 && message.indexOf("M3") > 0)
		{
			Font font = Static.bold(chatPanel.userFont);
			message = trimGarbage(message);
			if (message == null)
				return true;
			String text = source + " " + THINKS + ": " + message;
			display(new TextElement(font, actionColor, text, fromIndent));
			return true;
		}
		return false;
	}

	protected synchronized Element process(Object object)
	{
		if (!(object instanceof Message))
			return null;
		Message msg = (Message)object;
		String target = msg.target;
		String source = msg.source;
		String text = msg.text;
		if (isCTCP(text))
		{
			processCTCP(source, text);
			return null;
		}
		//	check for MSChat proprietary message
		if (text != null && text.startsWith("#"))
		{
			processMSChatMessage(source, text);
			return null;
		}
		if (isMSCHATAction(source, text))	// this method will display if true;
			return null;
		if (isMSCHATThink(source, text))	// this method will display if true;
			return null;
		text = trimGarbage(text);
		if (text == null)
			return null;
		Font font = msg.font;
		Color color = msg.color;
		if (source != null)
		{
			Font fromFont = font;
			Room room = chatPanel.getRoom();
			if (room != null)
			{
				User user = room.getUser(source);
				if (user != null && user.isOperator())
				{
					if (color == null)
						color = hostColor;
					fromFont = Static.bold(fromFont);
				}
			}
			String roomName = getRoomName();
			//	check to see if its a whisper
			if (roomName != null && target != null && target.equalsIgnoreCase(roomName))	//	this is not a whisper
				display(new TextElement(fromFont, color == null ? fromColor : color, source + " " + SAYS + ":", fromIndent));
			else	//	this is a whisper
				display(new TextElement(fromFont, whisperColor, source + " " + WHISPERS_TO + " " + target +":", fromIndent));
			//	display who from in specified font and color
			display(new TextElement(font, textColor, text, messageIndent));
		}
		else
		{
			//	no source, so it must be a system message
			//	add a LineReturnElement to ensure we start on our own line
			if (text.startsWith("Error"))
				color = errorColor;
			else if (color == null)
				color = systemColor;
			display(new TextElement(font, color, text, fromIndent));
		}
		return null;
	}

}
