irc.host=chloe1
irc.port=6667
listen.port=80
# idle time before terminating a irc client
# 30 seconds
client.timeout=30
# the maximum number of simultaneous connections
client.limit=500
default.page=index.html
templates=enhanced.irct,normal.irct,reverse.irct
