ObfuscateRoot("d:\\temp\\innertest");
//ObfuscateRoot("d:\\temp\\innerout");
OutputDir("d:\\temp\\innerout");
SourceName(false);
LineDebug(false);
LocalsDebug(false);
ExcludeClass(ALL, "test$intest");
DumpMap("D:\\temp\\sym.map");
