#ifndef __CCERROR_H__
#define __CCERROR_H__

#define CHATCLIENT_ERROR(e)					MAKE_SCODE(SEVERITY_ERROR, FACILITY_ITF, 0x7000 + e)
#define CHATCLIENT_SUCCESS(s)				MAKE_SCODE(SEVERITY_SUCCESS, FACILITY_NULL, 0x7000 + s)

#ifdef __cplusplus

const HRESULT	CC_E_INVALIDURL				= CHATCLIENT_ERROR(0x0001);
const HRESULT	CC_E_URLTOOLONG				= CHATCLIENT_ERROR(0x0002);
const HRESULT	CC_E_SERVERNAMETOOLONG		= CHATCLIENT_ERROR(0x0003);
const HRESULT	CC_E_CHANNELNAMETOOLONG		= CHATCLIENT_ERROR(0x0004);
const HRESULT	CC_E_CHANNELNAMETOOSHORT	= CHATCLIENT_ERROR(0x0005);
const HRESULT	CC_E_CHANNELPWDTOOLONG		= CHATCLIENT_ERROR(0x0006);
const HRESULT	CC_E_USERNAMETOOLONG		= CHATCLIENT_ERROR(0x0007);
const HRESULT	CC_E_NICKNAMETOOLONG		= CHATCLIENT_ERROR(0x0008);
const HRESULT	CC_E_USERPWDTOOLONG			= CHATCLIENT_ERROR(0x0009);
const HRESULT	CC_E_SECURITYTOOLONG		= CHATCLIENT_ERROR(0x000a);
const HRESULT	CC_E_TOPICTOOLONG			= CHATCLIENT_ERROR(0x000b);
const HRESULT	CC_E_CHANNEL_CHARS			= CHATCLIENT_ERROR(0x000c);
const HRESULT	CC_E_BUFFERTOOSMALL			= CHATCLIENT_ERROR(0x000d);
const HRESULT	CC_E_COULDNOTGETREALNAME	= CHATCLIENT_ERROR(0x000e);
const HRESULT	CC_E_SECURITYBLOCK			= CHATCLIENT_ERROR(0x000f);
const HRESULT	CC_E_ALREADYCONNECTING		= CHATCLIENT_ERROR(0x0010);
const HRESULT	CC_E_ALREADYCONNECTED		= CHATCLIENT_ERROR(0x0011);
const HRESULT	CC_E_ALREADYLOGGING			= CHATCLIENT_ERROR(0x0012);
const HRESULT	CC_E_ALREADYLOGGED			= CHATCLIENT_ERROR(0x0013);
const HRESULT	CC_E_ALREADYENTERINGCHANNEL	= CHATCLIENT_ERROR(0x0014);
const HRESULT	CC_E_NOTENTERINGCHANNEL		= CHATCLIENT_ERROR(0x0015);
const HRESULT	CC_E_ALREADYINCHANNEL		= CHATCLIENT_ERROR(0x0016);
const HRESULT	CC_E_UNICODENOTSUPPORTED	= CHATCLIENT_ERROR(0x0017);
const HRESULT	CC_E_ILLEGALUSER_MSN		= CHATCLIENT_ERROR(0x0018);
const HRESULT	CC_E_ILLEGALUSER_NTLM		= CHATCLIENT_ERROR(0x0019);
const HRESULT	CC_E_AUTHFAILED				= CHATCLIENT_ERROR(0x001a);
const HRESULT	CC_E_LOGINFAILED			= CHATCLIENT_ERROR(0x001b);

const HRESULT	CC_S_ENTERINGCANCELLED		= CHATCLIENT_SUCCESS(0x0001);

#else																	  

#define	CC_E_INVALIDURL				 CHATCLIENT_ERROR(0x0001)
#define	CC_E_URLTOOLONG				 CHATCLIENT_ERROR(0x0002)
#define	CC_E_SERVERNAMETOOLONG		 CHATCLIENT_ERROR(0x0003)
#define	CC_E_CHANNELNAMETOOLONG		 CHATCLIENT_ERROR(0x0004)
#define	CC_E_CHANNELNAMETOOSHORT	 CHATCLIENT_ERROR(0x0005)
#define	CC_E_CHANNELPWDTOOLONG		 CHATCLIENT_ERROR(0x0006)
#define	CC_E_USERNAMETOOLONG		 CHATCLIENT_ERROR(0x0007)
#define	CC_E_NICKNAMETOOLONG		 CHATCLIENT_ERROR(0x0008)
#define	CC_E_USERPWDTOOLONG			 CHATCLIENT_ERROR(0x0009)
#define	CC_E_SECURITYTOOLONG		 CHATCLIENT_ERROR(0x000a)
#define	CC_E_TOPICTOOLONG			 CHATCLIENT_ERROR(0x000b)
#define	CC_E_CHANNEL_CHARS			 CHATCLIENT_ERROR(0x000c)
#define	CC_E_BUFFERTOOSMALL			 CHATCLIENT_ERROR(0x000d)
#define	CC_E_COULDNOTGETREALNAME	 CHATCLIENT_ERROR(0x000e)
#define	CC_E_SECURITYBLOCK			 CHATCLIENT_ERROR(0x000f)
#define	CC_E_ALREADYCONNECTING		 CHATCLIENT_ERROR(0x0010)
#define	CC_E_ALREADYCONNECTED		 CHATCLIENT_ERROR(0x0011)
#define	CC_E_ALREADYLOGGING			 CHATCLIENT_ERROR(0x0012)
#define	CC_E_ALREADYLOGGED			 CHATCLIENT_ERROR(0x0013)
#define	CC_E_ALREADYENTERINGCHANNEL	 CHATCLIENT_ERROR(0x0014)
#define	CC_E_NOTENTERINGCHANNEL		 CHATCLIENT_ERROR(0x0015)
#define	CC_E_ALREADYINCHANNEL		 CHATCLIENT_ERROR(0x0016)
#define	CC_E_UNICODENOTSUPPORTED	 CHATCLIENT_ERROR(0x0017)
#define	CC_E_ILLEGALUSER_MSN		 CHATCLIENT_ERROR(0x0018)
#define	CC_E_ILLEGALUSER_NTLM		 CHATCLIENT_ERROR(0x0019)
#define	CC_E_AUTHFAILED				 CHATCLIENT_ERROR(0x001a)
#define	CC_E_LOGINFAILED			 CHATCLIENT_ERROR(0x001b)

#define CC_S_ENTERINGCANCELLED				CHATCLIENT_SUCCESS(0x0001)

#endif

#endif // __CCERROR_H__
