LineDebug(false);
ObfuscateRoot(".");
OutputDir("ob");
SourceName(false);
ExcludeClass(ALL, "IRCApplet");
ExcludeClass(ALL, "IRCClient");
ExcludeClass(ALL, "IRCListener");
ExcludeMethod(PUBLIC, "IRCApplet.*");
ExcludeMethod(PUBLIC, "IRCClient.*");
ExcludeMethod(PUBLIC, "IRCListener.*");
